name: Slate-Docs-CN

on:
  push:
    branches: [ master ]

# todo: 当 commit msg 中存在某些字符的时候不触发 actions
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      
      - name: Install Node
        uses: actions/setup-node@v1

      - name: Install gitbook-cli
        run: npm install gitbook-cli -g

      - name: Install gitbook
        run: gitbook fetch 3.2.3

      - name: Install gitbook dependency
        run: gitbook install

      - name: Build Book
        run: gitbook build --gitbook=3.2.3

      - name: Push
        working-directory: .
        run: |
          git checkout -b temp
          git add -A
          git -c user.name='github actions by ${{github.actor}}' -c user.email='NO' commit -m 'update docs' 
          git push -f "https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git" temp:gh


